name: Staging deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Add api remote origin
        run: |
          git remote add heroku-app https://heroku:b2f73873-ddee-45ee-8cc3-7e632ebe126a@git.heroku.com/app-html-1.git
      - name: Deploy api to Heroku
        run: |
          git subtree push --prefix xxx-app heroku-app main
